public enum StatementKind {
    NotAStatement,
    VariableDeclaration,
    FunctionDeclaration,
    ReturnStatement,
    FromStatement,
    NamespaceStatement,
    ForeachLoop,
    ForLoop,
    IfStatement,
    WhileStatement,
    DoWhileStatement,
    BreakStatement,
    ContinueStatement,
}